export const dynamic = "force-static";

export default function PrivacyPage() {
  return (
    <main style={{ minHeight: "100vh", background: "#ffffff", color: "#111827", fontFamily: "'Segoe UI', system-ui, Arial, sans-serif", lineHeight: 1.7 }}>

      <header style={{ borderBottom: "1px solid #e5e7eb", padding: "14px 32px" }}>
        <div style={{ maxWidth: 860, margin: "0 auto", display: "flex", alignItems: "center", justifyContent: "space-between", flexWrap: "wrap", gap: 12 }}>
          <a href="/" style={{ fontSize: 18, fontWeight: 700, color: "#111827", textDecoration: "none" }}>Trade Pilot</a>
          <nav style={{ display: "flex", gap: 20, fontSize: 13 }}>
            <a href="/terms"   style={{ color: "#6b7280", textDecoration: "none" }}>Terms of Service</a>
            <a href="/privacy" style={{ color: "#111827", fontWeight: 600, textDecoration: "none" }}>Privacy Policy</a>
          </nav>
        </div>
      </header>

      <div style={{ maxWidth: 860, margin: "0 auto", padding: "48px 32px" }}>
        <h1 style={{ fontSize: "clamp(24px, 4vw, 34px)", fontWeight: 800, color: "#111827", marginBottom: 6, marginTop: 0 }}>Privacy Policy</h1>
        <p style={{ fontSize: 13, color: "#9ca3af", marginBottom: 40 }}>Last updated: March 25, 2026</p>

        <p style={{ fontSize: 14, color: "#4b5563", marginBottom: 32 }}>
          This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
          We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
        </p>

        {/* Interpretation and Definitions */}
        <h2 style={{ fontSize: 20, fontWeight: 700, color: "#111827", marginBottom: 12, marginTop: 36 }}>Interpretation and Definitions</h2>

        <h3 style={{ fontSize: 16, fontWeight: 700, color: "#111827", marginBottom: 8, marginTop: 20 }}>Interpretation</h3>
        <p style={{ fontSize: 14, color: "#4b5563", marginBottom: 16 }}>
          The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
        </p>

        <h3 style={{ fontSize: 16, fontWeight: 700, color: "#111827", marginBottom: 8, marginTop: 20 }}>Definitions</h3>
        <p style={{ fontSize: 14, color: "#4b5563", marginBottom: 8 }}>For the purposes of this Privacy Policy:</p>
        <ul style={{ fontSize: 14, color: "#4b5563", paddingLeft: 24, marginBottom: 16, lineHeight: 1.9 }}>
          <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
          <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
          <li><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Privacy Policy) refers to Trade Pilot.</li>
          <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
          <li><strong>Country</strong> refers to: Italy</li>
          <li><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
          <li><strong>Personal Data</strong> (or &quot;Personal Information&quot;) is any information that relates to an identified or identifiable individual. We use &quot;Personal Data&quot; and &quot;Personal Information&quot; interchangeably unless a law uses a specific term.</li>
          <li><strong>Service</strong> refers to the Website.</li>
          <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
          <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
          <li><strong>Website</strong> refers to Trade Pilot, accessible from trade-pilot.net</li>
          <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
        </ul>

        {/* Collecting and Using Your Personal Data */}
        <h2 style={{ fontSize: 20, fontWeight: 700, color: "#111827", marginBottom: 12, marginTop: 40 }}>Collecting and Using Your Personal Data</h2>

        <h3 style={{ fontSize: 16, fontWeight: 700, color: "#111827", marginBottom: 8, marginTop: 20 }}>Types of Data Collected</h3>

        <h4 style={{ fontSize: 15, fontWeight: 700, color: "#374151", marginBottom: 8, marginTop: 14 }}>Personal Data</h4>
        <p style={{ fontSize: 14, color: "#4b5563", marginBottom: 8 }}>
          While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
        </p>
        <ul style={{ fontSize: 14, color: "#4b5563", paddingLeft: 24, marginBottom: 16, lineHeight: 1.9 }}>
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
        </ul>

        <h4 style={{ fontSize: 15, fontWeight: 700, color: "#374151", marginBottom: 8, marginTop: 14 }}>Usage Data</h4>
        <p style={{ fontSize: 14, color: "#4b5563", marginBottom: 8 }}>
          Usage Data is collected automatically when using the Service.
        </p>
        <p style={{ fontSize: 14, color: "#4b5563", marginBottom: 8 }}>
          Usage Data may include information such as Your Device&apos;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
        </p>
        <p style={{ fontSize: 14, color: "#4b5563", marginBottom: 8 }}>
          When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device&apos;s unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
        </p>
        <p style={{ fontSize: 14, color: "#4b5563", marginBottom: 16 }}>
          We may also collect information that Your browser sends whenever You visit Our Service or when You access the Service by or through a mobile device.
        </p>

        <h4 style={{ fontSize: 15, fontWeight: 700, color: "#374151", marginBottom: 8, marginTop: 14 }}>Tracking Technologies and Cookies</h4>
        <p style={{ fontSize: 14, color: "#4b5563", marginBottom: 8 }}>
          We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies We use include beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:
        </p>
        <ul style={{ fontSize: 14, color: "#4b5563", paddingLeft: 24, marginBottom: 8, lineHeight: 1.9 }}>
          <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</li>
          <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company to count users who have visited those pages or opened an email and for other related website statistics.</li>
        </ul>
        <p style={{ fontSize: 14, color: "#4b5563", marginBottom: 8 }}>
          Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.
        </p>
        <p style={{ fontSize: 14, color: "#4b5563", marginBottom: 8 }}>
          Where required by law, we use non-essential cookies (such as analytics, advertising, and remarketing cookies) only with Your consent. You can withdraw or change Your consent at any time using Our cookie preferences tool (if available) or through Your browser/device settings.
        </p>
        <p style={{ fontSize: 14, color: "#4b5563", marginBottom: 8 }}>We use both Session and Persistent Cookies for the purposes set out below:</p>
        <ul style={{ fontSize: 14, color: "#4b5563", paddingLeft: 24, marginBottom: 16, lineHeight: 1.9 }}>
          <li>
            <strong>Necessary / Essential Cookies</strong> — Type: Session Cookies — Administered by: Us.<br />
            Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts.
          </li>
          <li>
            <strong>Cookies Policy / Notice Acceptance Cookies</strong> — Type: Persistent Cookies — Administered by: Us.<br />
            Purpose: These Cookies identify if users have accepted the use of cookies on the Website.
          </li>
          <li>
            <strong>Functionality Cookies</strong> — Type: Persistent Cookies — Administered by: Us.<br />
            Purpose: These Cookies allow Us to remember choices You make when You use the Website, such as remembering your login details or language preference, to provide You with a more personal experience.
          </li>
        </ul>

        <h3 style={{ fontSize: 16, fontWeight: 700, color: "#111827", marginBottom: 8, marginTop: 24 }}>Use of Your Personal Data</h3>
        <p style={{ fontSize: 14, color: "#4b5563", marginBottom: 8 }}>The Company may use Personal Data for the following purposes:</p>
        <ul style={{ fontSize: 14, color: "#4b5563", paddingLeft: 24, marginBottom: 8, lineHeight: 1.9 }}>
          <li><strong>To provide and maintain our Service,</strong> including to monitor the usage of our Service.</li>
          <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service.</li>
          <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the contract for the services You have requested through the Service.</li>
          <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication regarding updates or informative communications related to the functionalities, products or contracted services.</li>
          <li><strong>To provide You with news, special offers, and general information</strong> about other goods, services and events which We offer that are similar to those that you have already purchased or inquired about, unless You have opted not to receive such information.</li>
          <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
          <li><strong>For business transfers:</strong> We may use Your Personal Data to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.</li>
          <li><strong>For other purposes:</strong> We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</li>
        </ul>
        <p style={{ fontSize: 14, color: "#4b5563", marginBottom: 8 }}>We may share Your Personal Data in the following situations:</p>
        <ul style={{ fontSize: 14, color: "#4b5563", paddingLeft: 24, marginBottom: 16, lineHeight: 1.9 }}>
          <li><strong>With Service Providers:</strong> We may share Your Personal Data with Service Providers to monitor and analyze the use of our Service, to contact You.</li>
          <li><strong>For business transfers:</strong> We may share or transfer Your Personal Data in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>
          <li><strong>With Affiliates:</strong> We may share Your Personal Data with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy.</li>
          <li><strong>With business partners:</strong> We may share Your Personal Data with Our business partners to offer You certain products, services or promotions.</li>
          <li><strong>With Your consent:</strong> We may disclose Your Personal Data for any other purpose with Your consent.</li>
        </ul>

        <h3 style={{ fontSize: 16, fontWeight: 700, color: "#111827", marginBottom: 8, marginTop: 24 }}>Retention of Your Personal Data</h3>
        <p style={{ fontSize: 14, color: "#4b5563", marginBottom: 8 }}>
          The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.
        </p>
        <p style={{ fontSize: 14, color: "#4b5563", marginBottom: 8 }}>Specific retention periods include:</p>
        <ul style={{ fontSize: 14, color: "#4b5563", paddingLeft: 24, marginBottom: 8, lineHeight: 1.9 }}>
          <li><strong>Account Information:</strong> retained for the duration of your account relationship plus up to 24 months after account closure.</li>
          <li><strong>Customer Support Data:</strong> Support tickets and correspondence up to 24 months from date of ticket closure.</li>
          <li><strong>Website analytics data</strong> (cookies, IP addresses, device identifiers): up to 24 months from date of collection.</li>
          <li><strong>Server logs</strong> (IP addresses, access times): up to 24 months for security monitoring and troubleshooting.</li>
        </ul>
        <p style={{ fontSize: 14, color: "#4b5563", marginBottom: 16 }}>
          Usage Data is retained in accordance with the retention periods described above, and may be retained longer only where necessary for security, fraud prevention, or legal compliance. We may retain Personal Data beyond the periods stated above where required by legal obligation, to establish or defend legal claims, or due to technical backup limitations.
        </p>

        <h3 style={{ fontSize: 16, fontWeight: 700, color: "#111827", marginBottom: 8, marginTop: 24 }}>Transfer of Your Personal Data</h3>
        <p style={{ fontSize: 14, color: "#4b5563", marginBottom: 16 }}>
          Your information, including Personal Data, is processed at the Company&apos;s operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of Your jurisdiction.
          Where required by applicable law, We will ensure that international transfers of Your Personal Data are subject to appropriate safeguards. The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy.
        </p>

        <h3 style={{ fontSize: 16, fontWeight: 700, color: "#111827", marginBottom: 8, marginTop: 24 }}>Delete Your Personal Data</h3>
        <p style={{ fontSize: 14, color: "#4b5563", marginBottom: 16 }}>
          You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. You may contact Us to request access to, correct, or delete any Personal Data that You have provided to Us. Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.
        </p>

        <h3 style={{ fontSize: 16, fontWeight: 700, color: "#111827", marginBottom: 8, marginTop: 24 }}>Disclosure of Your Personal Data</h3>
        <h4 style={{ fontSize: 15, fontWeight: 700, color: "#374151", marginBottom: 6, marginTop: 12 }}>Business Transactions</h4>
        <p style={{ fontSize: 14, color: "#4b5563", marginBottom: 10 }}>
          If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
        </p>
        <h4 style={{ fontSize: 15, fontWeight: 700, color: "#374151", marginBottom: 6, marginTop: 12 }}>Law Enforcement</h4>
        <p style={{ fontSize: 14, color: "#4b5563", marginBottom: 10 }}>
          Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
        </p>
        <h4 style={{ fontSize: 15, fontWeight: 700, color: "#374151", marginBottom: 6, marginTop: 12 }}>Other Legal Requirements</h4>
        <p style={{ fontSize: 14, color: "#4b5563", marginBottom: 8 }}>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
        <ul style={{ fontSize: 14, color: "#4b5563", paddingLeft: 24, marginBottom: 16, lineHeight: 1.9 }}>
          <li>Comply with a legal obligation</li>
          <li>Protect and defend the rights or property of the Company</li>
          <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
          <li>Protect the personal safety of Users of the Service or the public</li>
          <li>Protect against legal liability</li>
        </ul>

        <h3 style={{ fontSize: 16, fontWeight: 700, color: "#111827", marginBottom: 8, marginTop: 24 }}>Security of Your Personal Data</h3>
        <p style={{ fontSize: 14, color: "#4b5563", marginBottom: 16 }}>
          The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.
        </p>

        {/* Detailed Information on Processing */}
        <h2 style={{ fontSize: 20, fontWeight: 700, color: "#111827", marginBottom: 12, marginTop: 40 }}>Detailed Information on the Processing of Your Personal Data</h2>
        <p style={{ fontSize: 14, color: "#4b5563", marginBottom: 10 }}>
          The Service Providers We use may have access to Your Personal Data. These third-party vendors collect, store, use, process and transfer information about Your activity on Our Service in accordance with their Privacy Policies.
        </p>
        <h3 style={{ fontSize: 16, fontWeight: 700, color: "#111827", marginBottom: 8, marginTop: 20 }}>Usage, Performance and Miscellaneous</h3>
        <p style={{ fontSize: 14, color: "#4b5563", marginBottom: 8 }}>We may use third-party Service Providers to maintain and improve our Service:</p>
        <ul style={{ fontSize: 14, color: "#4b5563", paddingLeft: 24, marginBottom: 16, lineHeight: 1.9 }}>
          <li>
            <strong>Mouseflow</strong> — A session replay and heatmap tool that shows how visitors click, move, scroll, browse, and pay attention on websites. Operated by ApS.
            Information gathered by Mouseflow is held in accordance with its Privacy Policy at mouseflow.com/privacy/
          </li>
          <li>
            <strong>FreshDesk</strong> — A customer support software operated by Freshworks, Inc.
            Information gathered by FreshDesk is held in accordance with its Privacy Policy at freshworks.com/privacy/
          </li>
          <li>
            <strong>Google Places</strong> — A service that returns information about places using HTTP requests, operated by Google.
            Information gathered by Google Places is held in accordance with Google&apos;s Privacy Policy at google.com/intl/en/policies/privacy/
          </li>
        </ul>

        {/* Children's Privacy */}
        <h2 style={{ fontSize: 20, fontWeight: 700, color: "#111827", marginBottom: 12, marginTop: 40 }}>Children&apos;s Privacy</h2>
        <p style={{ fontSize: 14, color: "#4b5563", marginBottom: 16 }}>
          Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information from anyone under the age of 16. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 16 without verification of parental consent, We take steps to remove that information from Our servers.
        </p>

        {/* Links to Other Websites */}
        <h2 style={{ fontSize: 20, fontWeight: 700, color: "#111827", marginBottom: 12, marginTop: 40 }}>Links to Other Websites</h2>
        <p style={{ fontSize: 14, color: "#4b5563", marginBottom: 16 }}>
          Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party&apos;s site. We strongly advise You to review the Privacy Policy of every site You visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
        </p>

        {/* Changes */}
        <h2 style={{ fontSize: 20, fontWeight: 700, color: "#111827", marginBottom: 12, marginTop: 40 }}>Changes to this Privacy Policy</h2>
        <p style={{ fontSize: 14, color: "#4b5563", marginBottom: 16 }}>
          We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
        </p>

        {/* Contact Us */}
        <h2 style={{ fontSize: 20, fontWeight: 700, color: "#111827", marginBottom: 12, marginTop: 40 }}>Contact Us</h2>
        <p style={{ fontSize: 14, color: "#4b5563", marginBottom: 8 }}>If you have any questions about this Privacy Policy, You can contact us:</p>
        <ul style={{ fontSize: 14, color: "#4b5563", paddingLeft: 24, marginBottom: 40, lineHeight: 1.9 }}>
          <li>By email: <a href="mailto:info@tradepilot.com" style={{ color: "#059669" }}>info@tradepilot.com</a></li>
        </ul>
      </div>

      <footer style={{ borderTop: "1px solid #e5e7eb", padding: "20px 32px" }}>
        <div style={{ maxWidth: 860, margin: "0 auto", display: "flex", flexWrap: "wrap", alignItems: "center", justifyContent: "space-between", gap: 12, fontSize: 12, color: "#9ca3af" }}>
          <span>&copy; {new Date().getFullYear()} Trade Pilot. All rights reserved.</span>
          <div style={{ display: "flex", gap: 20 }}>
            <a href="/terms"   style={{ color: "#9ca3af", textDecoration: "none" }}>Terms of Service</a>
            <a href="/privacy" style={{ color: "#9ca3af", textDecoration: "none" }}>Privacy Policy</a>
          </div>
        </div>
      </footer>
    </main>
  );
}